/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PayrollDPoS } from "./PayrollDPoS";
export * as factories from "./factories";
export { PayrollDPoS__factory } from "./factories/PayrollDPoS__factory";
