/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PayrollDPoSInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEmployee"
      | "admin"
      | "adminWithdraw"
      | "changeAdmin"
      | "currentPeriodId"
      | "depositFunds"
      | "distributeBonus"
      | "employees"
      | "getAllEmployees"
      | "getEmployee"
      | "releaseAllSalaries"
      | "releaseSalary"
      | "removeEmployee"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "AdminWithdraw"
      | "BatchSalaryReleased"
      | "BonusDistributed"
      | "BonusPaid"
      | "Deposit"
      | "EmployeeAdded"
      | "EmployeeRemoved"
      | "SalaryReleased"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addEmployee",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "adminWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentPeriodId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeBonus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "employees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEmployees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseAllSalaries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseSalary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vote", values: [AddressLike]): string;

  decodeFunctionResult(
    functionFragment: "addEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentPeriodId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "employees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllEmployees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseAllSalaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminWithdrawEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchSalaryReleasedEvent {
  export type InputTuple = [totalAmount: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [totalAmount: bigint, timestamp: bigint];
  export interface OutputObject {
    totalAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BonusDistributedEvent {
  export type InputTuple = [
    periodId: BigNumberish,
    totalPool: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    periodId: bigint,
    totalPool: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    periodId: bigint;
    totalPool: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BonusPaidEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    periodId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    to: string,
    amount: bigint,
    periodId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    to: string;
    amount: bigint;
    periodId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeAddedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    name: string,
    salary: BigNumberish
  ];
  export type OutputTuple = [wallet: string, name: string, salary: bigint];
  export interface OutputObject {
    wallet: string;
    name: string;
    salary: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeRemovedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryReleasedEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [to: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    periodId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, periodId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    periodId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PayrollDPoS extends BaseContract {
  connect(runner?: ContractRunner | null): PayrollDPoS;
  waitForDeployment(): Promise<this>;

  interface: PayrollDPoSInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEmployee: TypedContractMethod<
    [_wallet: AddressLike, _name: string, _salary: BigNumberish],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  adminWithdraw: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  changeAdmin: TypedContractMethod<
    [_newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  currentPeriodId: TypedContractMethod<[], [bigint], "view">;

  depositFunds: TypedContractMethod<[], [void], "payable">;

  distributeBonus: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  employees: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, boolean] & {
        wallet: string;
        name: string;
        salary: bigint;
        lastPaid: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getAllEmployees: TypedContractMethod<[], [string[]], "view">;

  getEmployee: TypedContractMethod<
    [_wallet: AddressLike],
    [[string, string, bigint, bigint, boolean]],
    "view"
  >;

  releaseAllSalaries: TypedContractMethod<[], [void], "nonpayable">;

  releaseSalary: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  removeEmployee: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEmployee"
  ): TypedContractMethod<
    [_wallet: AddressLike, _name: string, _salary: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "adminWithdraw"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentPeriodId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositFunds"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "distributeBonus"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "employees"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, boolean] & {
        wallet: string;
        name: string;
        salary: bigint;
        lastPaid: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllEmployees"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEmployee"
  ): TypedContractMethod<
    [_wallet: AddressLike],
    [[string, string, bigint, bigint, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "releaseAllSalaries"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseSalary"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeEmployee"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "AdminWithdraw"
  ): TypedContractEvent<
    AdminWithdrawEvent.InputTuple,
    AdminWithdrawEvent.OutputTuple,
    AdminWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "BatchSalaryReleased"
  ): TypedContractEvent<
    BatchSalaryReleasedEvent.InputTuple,
    BatchSalaryReleasedEvent.OutputTuple,
    BatchSalaryReleasedEvent.OutputObject
  >;
  getEvent(
    key: "BonusDistributed"
  ): TypedContractEvent<
    BonusDistributedEvent.InputTuple,
    BonusDistributedEvent.OutputTuple,
    BonusDistributedEvent.OutputObject
  >;
  getEvent(
    key: "BonusPaid"
  ): TypedContractEvent<
    BonusPaidEvent.InputTuple,
    BonusPaidEvent.OutputTuple,
    BonusPaidEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeAdded"
  ): TypedContractEvent<
    EmployeeAddedEvent.InputTuple,
    EmployeeAddedEvent.OutputTuple,
    EmployeeAddedEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeRemoved"
  ): TypedContractEvent<
    EmployeeRemovedEvent.InputTuple,
    EmployeeRemovedEvent.OutputTuple,
    EmployeeRemovedEvent.OutputObject
  >;
  getEvent(
    key: "SalaryReleased"
  ): TypedContractEvent<
    SalaryReleasedEvent.InputTuple,
    SalaryReleasedEvent.OutputTuple,
    SalaryReleasedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "AdminWithdraw(address,uint256)": TypedContractEvent<
      AdminWithdrawEvent.InputTuple,
      AdminWithdrawEvent.OutputTuple,
      AdminWithdrawEvent.OutputObject
    >;
    AdminWithdraw: TypedContractEvent<
      AdminWithdrawEvent.InputTuple,
      AdminWithdrawEvent.OutputTuple,
      AdminWithdrawEvent.OutputObject
    >;

    "BatchSalaryReleased(uint256,uint256)": TypedContractEvent<
      BatchSalaryReleasedEvent.InputTuple,
      BatchSalaryReleasedEvent.OutputTuple,
      BatchSalaryReleasedEvent.OutputObject
    >;
    BatchSalaryReleased: TypedContractEvent<
      BatchSalaryReleasedEvent.InputTuple,
      BatchSalaryReleasedEvent.OutputTuple,
      BatchSalaryReleasedEvent.OutputObject
    >;

    "BonusDistributed(uint256,uint256,uint256)": TypedContractEvent<
      BonusDistributedEvent.InputTuple,
      BonusDistributedEvent.OutputTuple,
      BonusDistributedEvent.OutputObject
    >;
    BonusDistributed: TypedContractEvent<
      BonusDistributedEvent.InputTuple,
      BonusDistributedEvent.OutputTuple,
      BonusDistributedEvent.OutputObject
    >;

    "BonusPaid(address,uint256,uint256,uint256)": TypedContractEvent<
      BonusPaidEvent.InputTuple,
      BonusPaidEvent.OutputTuple,
      BonusPaidEvent.OutputObject
    >;
    BonusPaid: TypedContractEvent<
      BonusPaidEvent.InputTuple,
      BonusPaidEvent.OutputTuple,
      BonusPaidEvent.OutputObject
    >;

    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "EmployeeAdded(address,string,uint256)": TypedContractEvent<
      EmployeeAddedEvent.InputTuple,
      EmployeeAddedEvent.OutputTuple,
      EmployeeAddedEvent.OutputObject
    >;
    EmployeeAdded: TypedContractEvent<
      EmployeeAddedEvent.InputTuple,
      EmployeeAddedEvent.OutputTuple,
      EmployeeAddedEvent.OutputObject
    >;

    "EmployeeRemoved(address)": TypedContractEvent<
      EmployeeRemovedEvent.InputTuple,
      EmployeeRemovedEvent.OutputTuple,
      EmployeeRemovedEvent.OutputObject
    >;
    EmployeeRemoved: TypedContractEvent<
      EmployeeRemovedEvent.InputTuple,
      EmployeeRemovedEvent.OutputTuple,
      EmployeeRemovedEvent.OutputObject
    >;

    "SalaryReleased(address,uint256,uint256)": TypedContractEvent<
      SalaryReleasedEvent.InputTuple,
      SalaryReleasedEvent.OutputTuple,
      SalaryReleasedEvent.OutputObject
    >;
    SalaryReleased: TypedContractEvent<
      SalaryReleasedEvent.InputTuple,
      SalaryReleasedEvent.OutputTuple,
      SalaryReleasedEvent.OutputObject
    >;

    "VoteCast(address,address,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
